apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-deploy
  labels:
    app: converter
spec:
  replicas: 4
  selector:
    matchLabels:
      app: converter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
      - name: converter
        image: baseless060907/converter
        envFrom:
          - configMapRef:
              name: converter-config
          - secretRef:
              name: converter-secret